name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    env:
      IMAGE_NAME: petclinic
      CHART_DIR: helm/petclinic
      CHART_NAME: petclinic

    steps:
      - uses: actions/checkout@v4


      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - uses: azure/docker-login@v2
        with:
          login-server: ckcluster.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          REG="ckcluster.azurecr.io"
          docker build -t "$REG/$IMAGE_NAME:${{ github.sha }}" -t "$REG/$IMAGE_NAME:latest" .
          docker push "$REG/$IMAGE_NAME:${{ github.sha }}"
          docker push "$REG/$IMAGE_NAME:latest"

      - name: Push Helm chart to ACR (OCI)
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          REG="$ACR_LOGIN_SERVER"
          # Speichere Chart als OCI und pushe Tags (Commit-SHA und latest)
          helm chart save "$CHART_DIR" "$REG/helm/$CHART_NAME:${{ github.sha }}"
          helm chart save "$CHART_DIR" "$REG/helm/$CHART_NAME:latest"
          helm chart push "$REG/helm/$CHART_NAME:${{ github.sha }}"
          helm chart push "$REG/helm/$CHART_NAME:latest"
