name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    env:
      IMAGE_NAME: petclinic
      CHART_DIR: helm/petclinic
      CHART_NAME: petclinic

    steps:
      - uses: actions/checkout@v4


      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - uses: azure/docker-login@v2
        with:
          login-server: ckcluster.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          REG="ckcluster.azurecr.io"
          docker build -t "$REG/$IMAGE_NAME:${{ github.sha }}" -t "$REG/$IMAGE_NAME:latest" .
          docker push "$REG/$IMAGE_NAME:${{ github.sha }}"
          docker push "$REG/$IMAGE_NAME:latest"

      - name: Push Helm chart to ACR (OCI)
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          REG="ckcluster.azurecr.io"
          cd helm
          helm registry login "$REG" --username "${{ secrets.REGISTRY_USERNAME }}" --password "${{ secrets.REGISTRY_PASSWORD }}"
          CHART_VERSION="0.1.0-${GITHUB_SHA::7}"
          helm package "$CHART_DIR" --version "$CHART_VERSION"
          helm push "$CHART_NAME-$CHART_VERSION.tgz" "oci://$REG/helm"
